language: node_js
node_js: "9"
services: mongodb

cache:
  directories:
    - node_modules
    
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test
    - stage: deploy-dev
      if: branch = fix/pipeline
      before-install: npm install now --no-save
      script:
        - now --token $NOW_TOKEN

